CREATE DATABASE IF NOT EXISTS hrtrack;

ALTER DATABASE hrtrack
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON hrtrack.* TO 'hrtrack@%' IDENTIFIED BY 'hrtrack';
